### ISSUE TITLE
How to re-install after UI update

### ISSUE THREAD

**Issue by gearhead** [rern/RuneAudio_Addons#56]
So, if the UI is updated from 0.3 to 0.4 for example or the redis dbase reset, the redis DB still thinks it is all installed, but it is not. I deleted the keys for addons, refreshed PHP cache and did opcache_reset > addons.php and I think that did it. Would be nice if there was a cli script or a php page to reset it so it can be re-installed or reset...

**Comment by rern** [comment]
This will clear all Addons Menu database:
`redis-cli del addons`
