### ISSUE TITLE
Unclear issue with unclear issue in Addons menu

### ISSUE THREAD

**Issue by shikasta-net** [rern/RuneAudio_Addons#97]
i have just installed the addon manager on RuneOS 0.3b, UI 1.3b but I get an empty menu:
![screenshot from 2018-10-19 18-48-36](https://user-images.githubusercontent.com/1693155/47235016-a5506300-d3cf-11e8-8ecd-5537f8435c31.png).  Is it complaining about disk space?  The partition has 2GB of free space, so what's the deal?

The actual issue I wanted to flag is that the issue link in that image isn't clickable and I think is generated from this line (https://github.com/rern/RuneAudio_Addons/blob/5ad5a70176b95d659e53991bd3067ddbd0f7b2a3/srv/http/app/templates/addons.php#L31).

**Comment by shikasta-net** [comment]
correction, I have rune audio 0.4b but the SSH login reports it as 0.3b.

**Comment by zumbik** [comment]
I have some problem at rune audio 0.5beta.

**Comment by rern** [comment]
> correction, I have rune audio 0.4b but the SSH login reports it as 0.3b.

The actual 0.4b is [
http://www.runeaudio.com/forum/runeaudio-0-4-beta-for-raspberry-pi2-3-t4434.html](url). The one in download page has been ignored.


> I have some problem at rune audio 0.5beta.
Now 0.5 can run Addons. Try uninstall > install again.

**Comment by rern** [comment]
Fixed
